In [169]:
import tensorflow as tf
import pandas as pd
import numpy as np
from tensorflow import keras
from keras.models import Model, Sequential
from keras.layers import MaxPooling2D, Dropout, Dense, Flatten

In [713]:
df = pd.read_csv('ecg.csv', header=None)

In [715]:
df

0         1         2         3         4         5    ...       135       136       137       138       139  140
0    -0.112522 -2.827204 -3.773897 -4.349751 -4.376041 -3.474986  ...  0.257740  0.228077  0.123431  0.925286  0.193137  1.0
1    -1.100878 -3.996840 -4.285843 -4.506579 -4.022377 -3.234368  ...  0.555784  0.476333  0.773820  1.119621 -1.436250  1.0
2    -0.567088 -2.593450 -3.874230 -4.584095 -4.187449 -3.151462  ... -0.713683 -0.532197  0.321097  0.904227 -0.421797  1.0
3     0.490473 -1.914407 -3.616364 -4.318823 -4.268016 -3.881110  ...  0.952074  0.990133  1.086798  1.403011 -0.383564  1.0
4     0.800232 -0.874252 -2.384761 -3.973292 -4.338224 -3.802422  ...  1.277392  0.960304  0.971020  1.614392  1.421456  1.0
...        ...       ...       ...       ...       ...       ...  ...       ...       ...       ...       ...       ...  ...
4993  0.608558 -0.335651 -0.990948 -1.784153 -2.626145 -2.957065  ...  2.017396  1.704358  1.688542  1.629593  1.342651  0.0
4994 -2.060402 -2.860116 -3.405074 -3.748719 -3.513561 -3.006545  ...  1.819747  1.534767  1.696818  1.483832  1.047612  0.0
4995 -1.122969 -2.252925 -2.867628 -3.358605 -3.167849 -2.638360  ... -4.176790 -4.009720 -2.874136 -2.008369 -1.808334  0.0
4996 -0.547705 -1.889545 -2.839779 -3.457912 -3.929149 -3.966026  ...  1.437702  1.193433  1.261335  1.150449  0.804932  0.0
4997 -1.351779 -2.209006 -2.520225 -3.061475 -3.065141 -3.030739  ... -3.627311 -3.437038 -2.260023 -1.577823 -0.684531  0.0

[4998 rows x 141 columns]

In [174]:
x = df.drop(140, axis=1)

In [175]:
x

0         1         2         3         4    ...       135       136       137       138       139
0    -0.112522 -2.827204 -3.773897 -4.349751 -4.376041  ...  0.257740  0.228077  0.123431  0.925286  0.193137
1    -1.100878 -3.996840 -4.285843 -4.506579 -4.022377  ...  0.555784  0.476333  0.773820  1.119621 -1.436250
2    -0.567088 -2.593450 -3.874230 -4.584095 -4.187449  ... -0.713683 -0.532197  0.321097  0.904227 -0.421797
3     0.490473 -1.914407 -3.616364 -4.318823 -4.268016  ...  0.952074  0.990133  1.086798  1.403011 -0.383564
4     0.800232 -0.874252 -2.384761 -3.973292 -4.338224  ...  1.277392  0.960304  0.971020  1.614392  1.421456
...        ...       ...       ...       ...       ...  ...       ...       ...       ...       ...       ...
4993  0.608558 -0.335651 -0.990948 -1.784153 -2.626145  ...  2.017396  1.704358  1.688542  1.629593  1.342651
4994 -2.060402 -2.860116 -3.405074 -3.748719 -3.513561  ...  1.819747  1.534767  1.696818  1.483832  1.047612
4995 -1.122969 -2.252925 -2.867628 -3.358605 -3.167849  ... -4.176790 -4.009720 -2.874136 -2.008369 -1.808334
4996 -0.547705 -1.889545 -2.839779 -3.457912 -3.929149  ...  1.437702  1.193433  1.261335  1.150449  0.804932
4997 -1.351779 -2.209006 -2.520225 -3.061475 -3.065141  ... -3.627311 -3.437038 -2.260023 -1.577823 -0.684531

[4998 rows x 140 columns]

In [176]:
y = df[140]

In [178]:
y

0       1.0
1       1.0
2       1.0
3       1.0
4       1.0
       ... 
4993    0.0
4994    0.0
4995    0.0
4996    0.0
4997    0.0
Name: 140, Length: 4998, dtype: float64

In [180]:
from sklearn.model_selection import train_test_split

In [639]:
x_train, x_test, y_train, y_test = train_test_split(x, y,  test_size=0.15, stratify=y)

In [641]:
x_train

0         1         2         3         4    ...       135       136       137       138       139
4689  0.255914 -0.197584 -0.620383 -1.042968 -1.485946  ... -2.323737 -2.763917 -2.979507 -2.635076 -2.186362
3805  0.298969 -1.041819 -1.929145 -2.708805 -3.167397  ... -3.125980 -2.702669 -1.572757 -0.942015  0.229110
1624  1.284861  0.040518 -1.990933 -3.143235 -4.031646  ...  1.351192  1.249365  0.829225  0.102140  0.223482
4874 -0.507884 -1.097878 -1.486035 -1.808509 -2.039048  ... -4.359088 -3.931881 -2.736457 -1.924481 -1.001451
3695 -0.860987 -1.709675 -2.147438 -2.940472 -3.014905  ... -3.467922 -3.280236 -2.373644 -1.818613 -0.225012
...        ...       ...       ...       ...       ...  ...       ...       ...       ...       ...       ...
3999 -0.484100 -1.373759 -1.842089 -2.516398 -2.591785  ... -2.571358 -1.547036 -0.448469 -0.004507  0.805959
1268  0.224270 -1.222339 -2.359306 -3.388400 -4.258217  ... -0.487922 -0.923496 -1.173298 -0.587561 -0.032608
2447 -1.350473 -3.526396 -4.323904 -4.153862 -3.370095  ...  1.416996  0.909783  1.032763  1.096176 -0.172772
449   0.898367  0.235221 -0.529196 -1.371396 -2.019502  ... -3.819824 -3.313858 -2.183761 -1.460414 -0.126323
665   0.209932 -1.989626 -3.577049 -3.923764 -3.965757  ...  0.921225  0.848173  0.819750  0.240846 -1.889941

[4248 rows x 140 columns]

In [642]:
train_index = y_train[y_train==1].index

In [643]:
train_index

Index([1624,   84,  219, 1026,   82,  895, 2922,  904, 1822, 2933,
       ...
       1312, 1224,  999,  622, 1682,  741, 3061, 1268, 2447,  665],
      dtype='int64', length=2481)

In [644]:
x_train.index

Index([4689, 3805, 1624, 4874, 3695, 4965,   84, 3949,  219, 1026,
       ...
        622, 4869, 1682,  741, 3061, 3999, 1268, 2447,  449,  665],
      dtype='int64', length=4248)

In [645]:
train_data = x_train.loc[train_index]

In [646]:
train_data

0         1         2         3         4    ...       135       136       137       138       139
1624  1.284861  0.040518 -1.990933 -3.143235 -4.031646  ...  1.351192  1.249365  0.829225  0.102140  0.223482
84    3.206123  1.825166 -0.926295 -2.454381 -3.619700  ...  0.243575  0.412066  0.282026 -0.255233  0.149609
219  -2.858707 -3.217407 -3.219644 -2.939891 -2.635886  ...  0.393868  0.707027  0.656579  0.581160  0.699394
1026 -1.309953 -3.576316 -4.441968 -4.374130 -4.126832  ...  0.391909  0.208535  0.460480  1.158692 -0.373392
82   -0.028530 -2.289492 -3.549733 -4.014579 -4.056989  ...  0.587181  0.870994  1.318106  0.416291 -2.252547
...        ...       ...       ...       ...       ...  ...       ...       ...       ...       ...       ...
741   0.899409 -0.871262 -2.528711 -3.539998 -4.321528  ...  1.267768  0.934952  0.392740 -0.387630  0.034472
3061 -1.349433 -3.477942 -3.977980 -4.325376 -3.924544  ...  0.735853  0.679551  0.976040  0.655732 -1.311087
1268  0.224270 -1.222339 -2.359306 -3.388400 -4.258217  ... -0.487922 -0.923496 -1.173298 -0.587561 -0.032608
2447 -1.350473 -3.526396 -4.323904 -4.153862 -3.370095  ...  1.416996  0.909783  1.032763  1.096176 -0.172772
665   0.209932 -1.989626 -3.577049 -3.923764 -3.965757  ...  0.921225  0.848173  0.819750  0.240846 -1.889941

[2481 rows x 140 columns]

In [647]:
from sklearn.preprocessing import MinMaxScaler

In [648]:
min_max_scaler = MinMaxScaler(feature_range=(0,1))

In [649]:
min_max_scaler

MinMaxScaler()

In [650]:
x_train_scaled = min_max_scaler.fit_transform(train_data.copy())

In [655]:
x_test_scaled = min_max_scaler.transform(x_test.copy())

In [656]:
x_test_scaled

array([[0.54965604, 0.46802633, 0.2664242 , ..., 0.76296349, 0.87117822,
        0.77203227],
       [0.49352105, 0.56255779, 0.57132684, ..., 0.2522814 , 0.36300639,
        0.52958322],
       [0.56804955, 0.50383538, 0.32661176, ..., 0.73113084, 0.8323312 ,
        0.7478731 ],
       ...,
       [0.49076526, 0.47113874, 0.41071186, ..., 0.30862966, 0.39525802,
        0.51641949],
       [0.37343582, 0.25406346, 0.11409811, ..., 0.59023758, 0.68472109,
        0.68679345],
       [0.44814552, 0.39033993, 0.28938474, ..., 0.47877613, 0.34649497,
        0.27076234]])

In [717]:
x_train_scaled

array([[0.66515611, 0.65629002, 0.46291125, ..., 0.69908995, 0.6038807 ,
        0.65495479],
       [0.83989833, 0.84157301, 0.62089804, ..., 0.62920661, 0.55328801,
        0.64585655],
       [0.28829113, 0.31805069, 0.28057693, ..., 0.67704112, 0.67169477,
        0.713568  ],
       ...,
       [0.56869342, 0.52517967, 0.40824659, ..., 0.44334558, 0.50624087,
        0.62341464],
       [0.42546777, 0.28597132, 0.11671033, ..., 0.72508402, 0.74460473,
        0.60615209],
       [0.56738941, 0.44551955, 0.22753991, ..., 0.69787987, 0.62351707,
        0.39466562]])

In [658]:
class Autoencoder(Model):
    def __init__(self, output_units, code_size=8):
        super().__init__()

        self.encoder = Sequential([
            Dense(64, activation='relu'),
            Dropout(0.2),
            Dense(32, activation='relu'),
            Dropout(0.2),
            Dense(16, activation='relu'),
            Dropout(0.2),
            Dense(code_size, activation='relu')
        ])

        self.decoder = Sequential([
            Dense(16, activation='relu'),
            Dropout(0.2),
            Dense(32, activation='relu'),
            Dropout(0.2),
            Dense(64, activation='relu'),
            Dropout(0.2),
            Dense(output_units, activation='sigmoid')
        ])

    def call(self, input_units):
        encode = self.encoder(input_units)
        decode = self.decoder(encode)
        return decode

In [659]:
x_train_scaled.shape

(2481, 140)

In [660]:
model = Autoencoder(output_units=x_train_scaled.shape[1])

In [661]:
model.summary()

Model: "autoencoder_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ sequential_16 (Sequential)           │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ sequential_17 (Sequential)           │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [662]:
model.compile(optimizer='adam', loss='msle', metrics=['mse'])

In [663]:
print(x_train_scaled.shape)  # Ensure matches the model's expected input
print(x_test_scaled.shape)

(2481, 140)
(750, 140)


In [664]:
history = model.fit(x_train_scaled, x_train_scaled, batch_size=512, validation_data=(x_test_scaled, x_test_scaled), epochs=30)

Epoch 1/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 4s 97ms/step - loss: 0.0112 - mse: 0.0251 - val_loss: 0.0132 - val_mse: 0.0308
Epoch 2/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0110 - mse: 0.0245 - val_loss: 0.0132 - val_mse: 0.0306
Epoch 3/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0107 - mse: 0.0238 - val_loss: 0.0130 - val_mse: 0.0303
Epoch 4/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0102 - mse: 0.0228 - val_loss: 0.0129 - val_mse: 0.0300
Epoch 5/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0097 - mse: 0.0216 - val_loss: 0.0127 - val_mse: 0.0294
Epoch 6/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0091 - mse: 0.0203 - val_loss: 0.0123 - val_mse: 0.0287
Epoch 7/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0085 - mse: 0.0190 - val_loss: 0.0119 - val_mse: 0.0277
Epoch 8/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0078 - mse: 0.0173 - val_loss: 0.0115 - val_mse: 0.0267
Epoch 9/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0073 - mse: 0.0162 - 

In [665]:
pred1 = model.predict(x_train_scaled)

78/78 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step


In [666]:
pred1_error = keras.losses.msle(pred1, x_train_scaled)

In [667]:
pred1_error

<tf.Tensor: shape=(2481,), dtype=float64, numpy=
array([0.00260053, 0.01220255, 0.00999391, ..., 0.00285355, 0.00088742,
       0.0009402 ])>

In [673]:
threshold = np.mean(pred1_error.numpy()) + np.std(pred1_error.numpy()) 

In [676]:
threshold

0.005223271000945414

In [683]:
pred2 = model.predict(x_test_scaled)

24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


In [684]:
pred2_error = keras.losses.msle(pred2, x_test_scaled)

In [685]:
ana = pd.Series(pred2_error) > threshold

In [686]:
pre = np.where(ana, 0.0, 1.0)

In [687]:
ana

0      False
1       True
2      False
3       True
4       True
       ...  
745    False
746    False
747     True
748    False
749    False
Length: 750, dtype: bool

In [688]:
pre

array([1., 0., 1., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 0., 1., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 1., 1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 0., 1.,
       1., 0., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1.,
       1., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 1., 0., 1., 0., 0.,
       1., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1.,
       1., 0., 1., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1., 1., 0.,
       1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
       0., 1., 1., 1., 1.

In [689]:
from sklearn.metrics import accuracy_score

In [690]:
y_test

2036    1.0
4952    0.0
581     1.0
4608    0.0
486     0.0
       ... 
1716    1.0
1557    1.0
4510    0.0
1535    1.0
70      1.0
Name: 140, Length: 750, dtype: float64

In [691]:
acc = accuracy_score(pre, y_test)

In [692]:
acc

0.936